replicaCount: 1

image:
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 50m
    memory: 1024Mi

mlflow-postgresql:
  image:
    tag: 11.11.0-debian-10-r92
  postgresqlPassword: postgres
  fullnameOverride: mlflow-postgresql
