replicaCount: 1

image:
  pullPolicy: IfNotPresent

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 50m
    memory: 1024Mi

mlflow-postgresql:
  image:
    tag: 16.1.0-debian-11-r27
  postgresqlPassword: postgres
  fullnameOverride: mlflow-postgresql
  global:
    postgresql:
      auth:
        postgresPassword: postgres
