apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow.name" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mlflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mlflow.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mlflow.name" . }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "ghcr.io/aisotag/docker/mlflow:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.name" . }}
                  key: BACKEND_STORE_URI
            - name: ARTIFACTS_DESTINATION
              value: '/home/cnb/artifacts/{{ .Release.Namespace }}/{{ include "mlflow.name" . }}/artifacts'
            - name: HOST
              value: '0.0.0.0'
            - name: PORT
              value: '8080'
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/cnb/artifacts/
              name: artifact-store
      initContainers:
        - name: {{ .Chart.Name }}-db-migration
          image: "ghcr.io/aisotag/docker/mlflow:{{ .Chart.AppVersion }}"
          command:
            - mlflow
            - db
            - upgrade
            - $(BACKEND_STORE_URI)
          env:
            - name: BACKEND_STORE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "mlflow.name" . }}
                  key: BACKEND_STORE_URI
      volumes:
        - name: artifact-store
          nfs:
            server: {{ .Values.sharedNfs.host }}
            path: {{ .Values.sharedNfs.path }}