apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 512m
  name: {{ include "mlflow.name" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: 'mlflow.{{ .Values.domain }}'
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "mlflow.name" . }}
                port:
                  number: 80
  tls:
    - hosts:
        - '*.{{ .Values.domain }}' # The domain for the wildcard certificate
      secretName: {{ include "mlflow.name" . }}-cert # The secret in which the TLS certificate should be stored.
