apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.name" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  BACKEND_STORE_URI: {{ .Values.backendStoreUri }}
