apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.name" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
